version: '3.8'

services:
  synchronizer:
    image: digitalasset/canton-open-source:latest
    container_name: canton-synchronizer
    ports:
      - "5018:5018"
      - "5019:5019"
    volumes:
      - ./canton/synchronizer.conf:/canton/synchronizer.conf:ro
    command: daemon --config /canton/synchronizer.conf
    restart: unless-stopped
    networks:
      - canton-network

  participant1:
    image: digitalasset/canton-open-source:latest
    container_name: canton-participant1
    ports:
      - "5011:5011"
      - "5012:5012"
      - "7011:7011"
    volumes:
      - ./canton/participant1.conf:/canton/participant1.conf:ro
      - ../daml/.daml/dist/payment-demo-0.0.1.dar:/canton/payment-demo-0.0.1.dar:ro
    command: daemon --config /canton/participant1.conf
    restart: unless-stopped
    networks:
      - canton-network
    depends_on:
      - synchronizer

  participant2:
    image: digitalasset/canton-open-source:latest
    container_name: canton-participant2
    ports:
      - "5021:5021"
      - "5022:5022"
      - "7021:7021"
    volumes:
      - ./canton/participant2.conf:/canton/participant2.conf:ro
      - ../daml/.daml/dist/payment-demo-0.0.1.dar:/canton/payment-demo-0.0.1.dar:ro
    command: daemon --config /canton/participant2.conf
    restart: unless-stopped
    networks:
      - canton-network
    depends_on:
      - synchronizer

  participant3:
    image: digitalasset/canton-open-source:latest
    container_name: canton-participant3
    ports:
      - "5031:5031"
      - "5032:5032"
      - "7031:7031"
    volumes:
      - ./canton/participant3.conf:/canton/participant3.conf:ro
      - ../daml/.daml/dist/payment-demo-0.0.1.dar:/canton/payment-demo-0.0.1.dar:ro
    command: daemon --config /canton/participant3.conf
    restart: unless-stopped
    networks:
      - canton-network
    depends_on:
      - synchronizer

networks:
  canton-network:
    driver: bridge
